"""Advanced PDF report generator with robust error handling, compliance checks,
section breakdowns, annotations, and standards references.

This module provides generate_advanced_pdf_report() as a crash-safe alternative
to the basic PDF generator in report.py.
"""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any

from fpdf import FPDF


def _safe(val: Any, default: str = "N/A") -> str:
    """Safely convert any value to a string, handling None/empty."""
    if val is None:
        return default
    s = str(val).strip()
    return s if s else default


def _sanitize(text: str) -> str:
    """Remove characters that FPDF2 cannot encode in latin-1."""
    if not text:
        return ""
    # Replace common unicode chars with ASCII equivalents
    replacements = {
        "\u2013": "-", "\u2014": "--", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "-", "\u2026": "...",
        "\u2192": "->", "\u2190": "<-", "\u2191": "^", "\u2193": "v",
        "\u2714": "[OK]", "\u2716": "[X]", "\u2713": "[v]",
        "\u2588": "#", "\u2591": ".", "\u2592": ":", "\u2593": "#",
        "\u25cf": "*", "\u25cb": "o", "\u25a0": "#", "\u25a1": "[]",
        "\u2605": "*", "\u2606": "*", "\u2603": "*",
        "\u00b0": "deg", "\u00b1": "+/-", "\u00d7": "x", "\u00f7": "/",
        "\u2264": "<=", "\u2265": ">=", "\u2260": "!=",
        "\u221e": "inf", "\u03c0": "pi",
        "\u2550": "=", "\u2500": "-", "\u2502": "|", "\u253c": "+",
        "\u250c": "+", "\u2510": "+", "\u2514": "+", "\u2518": "+",
        "\u2501": "=", "\u2503": "|", "\u254b": "+",
    }
    for uchar, replacement in replacements.items():
        text = text.replace(uchar, replacement)
    # Strip any remaining non-latin1 characters
    try:
        text.encode("latin-1")
    except UnicodeEncodeError:
        text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text


class AdvancedPDF(FPDF):
    """Custom FPDF subclass with header/footer and helper methods."""

    def __init__(self, project_name: str):
        super().__init__()
        self.project_name = _sanitize(project_name)
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has no header
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, f"ConstructAI QA/QC Report - {self.project_name}", align="L")
        self.cell(0, 5, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, 12, 200, 12)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, "CONFIDENTIAL - Generated by ConstructAI Platform", align="C")

    def section_title(self, number: str, title: str):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(31, 78, 121)
        self.cell(0, 12, _sanitize(f"{number}. {title}"), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(31, 78, 121)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def subsection_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(46, 117, 182)
        self.cell(0, 9, _sanitize(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text: str, bold: bool = False):
        self.set_font("Helvetica", "B" if bold else "", 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, _sanitize(text))
        self.ln(1)

    def severity_badge(self, severity: str):
        colors = {
            "Critical": (204, 0, 0),
            "Major": (255, 165, 0),
            "Minor": (0, 112, 192),
        }
        r, g, b = colors.get(severity, (100, 100, 100))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        w = self.get_string_width(severity) + 6
        self.cell(w, 6, severity, fill=True, new_x="END")
        self.set_text_color(51, 51, 51)

    def add_table(self, headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None):
        if not col_widths:
            total = 190
            col_widths = [total / len(headers)] * len(headers)

        # Header
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(31, 78, 121)
        self.set_text_color(255, 255, 255)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 7, _sanitize(header), border=1, fill=True, align="C")
        self.ln()

        # Rows
        self.set_font("Helvetica", "", 8)
        self.set_text_color(51, 51, 51)
        for r_idx, row in enumerate(rows):
            if r_idx % 2 == 0:
                self.set_fill_color(232, 240, 254)
            else:
                self.set_fill_color(255, 255, 255)
            max_h = 7
            for i, val in enumerate(row):
                w = col_widths[i] if i < len(col_widths) else 30
                self.cell(w, max_h, _sanitize(str(val or ""))[:50], border=1, fill=True)
            self.ln()


def generate_advanced_pdf_report(
    project_name: str,
    project_description: str = "",
    building_codes: list[str] | None = None,
    issues: list[dict[str, Any]] | None = None,
    ncrs: list[dict[str, Any]] | None = None,
    rfis: list[dict[str, Any]] | None = None,
    summary: dict[str, Any] | None = None,
    audit_logs: list[dict[str, Any]] | None = None,
    version_data: dict[str, list[dict[str, Any]]] | None = None,
) -> bytes:
    """Generate a comprehensive, crash-safe advanced PDF report."""

    issues = issues or []
    ncrs = ncrs or []
    rfis = rfis or []
    building_codes = building_codes or []
    audit_logs = audit_logs or []
    version_data = version_data or {}
    summary = summary or {}

    pdf = AdvancedPDF(project_name)

    now = datetime.utcnow()
    report_date = now.strftime("%B %d, %Y")
    doc_ref = f"CAI-QA-{now.strftime('%Y%m%d')}-001"

    # Severity counts
    critical = sum(1 for i in issues if _safe(i.get("severity")) == "Critical")
    major = sum(1 for i in issues if _safe(i.get("severity")) == "Major")
    minor = sum(1 for i in issues if _safe(i.get("severity")) == "Minor")
    fixed = sum(1 for i in issues if _safe(i.get("status")) == "Fixed")
    open_count = sum(1 for i in issues if _safe(i.get("status")) in ("Open", "Accepted"))

    # ══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.ln(40)

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(31, 78, 121)
    pdf.cell(0, 15, "QUALITY ASSURANCE / QUALITY CONTROL", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 18)
    pdf.set_text_color(46, 117, 182)
    pdf.cell(0, 12, "AI-POWERED ADVANCED REVIEW REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)
    pdf.set_draw_color(31, 78, 121)
    pdf.line(40, pdf.get_y(), 170, pdf.get_y())
    pdf.ln(10)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(80, 80, 80)
    info_lines = [
        f"Project: {_safe(project_name)}",
        f"Document Reference: {doc_ref}",
        f"Report Date: {report_date}",
        "Classification: CONFIDENTIAL",
        "Platform: ConstructAI QA/QC Review",
    ]
    for line in info_lines:
        pdf.cell(0, 8, _sanitize(line), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)

    # Quick stats box
    pdf.set_fill_color(240, 245, 255)
    pdf.set_draw_color(31, 78, 121)
    pdf.rect(30, pdf.get_y(), 150, 35, style="DF")
    y_box = pdf.get_y() + 5
    pdf.set_xy(35, y_box)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(31, 78, 121)
    pdf.cell(0, 7, f"Total Findings: {len(issues)}   |   Critical: {critical}   |   Major: {major}   |   Minor: {minor}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(35, y_box + 10)
    pdf.cell(0, 7, f"NCRs: {len(ncrs)}   |   RFIs: {len(rfis)}   |   Fixed: {fixed}   |   Open: {open_count}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(35, y_box + 20)
    conf = summary.get("overall_confidence")
    conf_str = f"{round(conf * 100)}%" if conf is not None else "N/A"
    pdf.cell(0, 7, f"Review Confidence: {conf_str}", new_x="LMARGIN", new_y="NEXT")

    # ══════════════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("0", "Table of Contents")

    toc = [
        "1. Executive Summary",
        "2. Scope & Methodology",
        "3. Compliance Assessment Matrix",
        "4. Severity Distribution",
        "5. Detailed Findings (by Section)",
        "6. Annotations & Location Map",
        "7. Non-Conformance Reports (NCRs)",
        "8. Requests for Information (RFIs)",
        "9. Standards References",
        "10. Audit Trail",
    ]
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(31, 78, 121)
    for item in toc:
        pdf.cell(0, 7, _sanitize(item), new_x="LMARGIN", new_y="NEXT")

    # ══════════════════════════════════════════════════════════════════════════
    # 1. EXECUTIVE SUMMARY
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("1", "Executive Summary")

    if project_description:
        pdf.body_text(f"Project Description: {project_description}", bold=True)

    if summary.get("executive_summary"):
        pdf.body_text(summary["executive_summary"])

    if summary.get("confidence_reasoning"):
        pdf.body_text(f"Confidence Reasoning: {summary['confidence_reasoning']}")

    risk_areas = summary.get("top_risk_areas", [])
    if risk_areas:
        pdf.subsection_title("Top Risk Areas")
        for area in risk_areas:
            pdf.body_text(f"  - {area}")

    # Summary statistics table
    pdf.ln(3)
    pdf.subsection_title("Summary Statistics")
    pdf.add_table(
        ["Metric", "Count"],
        [
            ["Total Findings", str(len(issues))],
            ["Critical", str(critical)],
            ["Major", str(major)],
            ["Minor", str(minor)],
            ["NCRs Raised", str(len(ncrs))],
            ["RFIs Raised", str(len(rfis))],
            ["Fixed Issues", str(fixed)],
            ["Open Issues", str(open_count)],
        ],
        [95, 95],
    )

    # ══════════════════════════════════════════════════════════════════════════
    # 2. SCOPE & METHODOLOGY
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("2", "Scope & Methodology")

    pdf.body_text(
        f'This report presents AI-powered QA/QC findings for "{_safe(project_name)}". '
        "The review covers structural integrity, code compliance, safety, "
        "constructability, and documentation completeness."
    )

    pdf.subsection_title("AI Review Agents")
    agents = [
        ("Speed Agent (Groq)", "Rapid checklist screening for common violations"),
        ("Vision Agent (Gemini)", "Visual analysis of engineering drawings"),
        ("Reasoning Agent (Groq)", "Deep code compliance cross-referencing"),
        ("Summary Agent", "Aggregation and executive summarization"),
    ]
    for name, desc in agents:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(51, 51, 51)
        pdf.cell(55, 6, _sanitize(f"{name}: "), new_x="END")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, _sanitize(desc), new_x="LMARGIN", new_y="NEXT")

    # ══════════════════════════════════════════════════════════════════════════
    # 3. COMPLIANCE ASSESSMENT MATRIX
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("3", "Compliance Assessment Matrix")

    # Group findings by code_clause
    code_groups: dict[str, list] = {}
    for iss in issues:
        clause = _safe(iss.get("code_clause"), "General")
        code_groups.setdefault(clause, []).append(iss)

    if code_groups:
        rows = []
        for clause, group_issues in sorted(code_groups.items()):
            c = sum(1 for i in group_issues if _safe(i.get("severity")) == "Critical")
            m = sum(1 for i in group_issues if _safe(i.get("severity")) == "Major")
            mi = sum(1 for i in group_issues if _safe(i.get("severity")) == "Minor")
            status = "NON-COMPLIANT" if c > 0 else "NEEDS REVIEW" if m > 0 else "OBSERVATION"
            rows.append([clause[:30], str(len(group_issues)), str(c), str(m), str(mi), status])

        pdf.add_table(
            ["Code/Standard", "Findings", "Crit", "Maj", "Min", "Status"],
            rows,
            [45, 22, 18, 18, 18, 35],
        )
    else:
        pdf.body_text("No compliance issues identified.")

    # ══════════════════════════════════════════════════════════════════════════
    # 4. SEVERITY DISTRIBUTION
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("4", "Severity Distribution")

    pdf.subsection_title("By Severity and Status")
    dist_rows = []
    for sev in ["Critical", "Major", "Minor"]:
        sev_issues = [i for i in issues if _safe(i.get("severity")) == sev]
        dist_rows.append([
            sev,
            str(sum(1 for i in sev_issues if _safe(i.get("status")) == "Open")),
            str(sum(1 for i in sev_issues if _safe(i.get("status")) == "Accepted")),
            str(sum(1 for i in sev_issues if _safe(i.get("status")) == "Fixed")),
            str(sum(1 for i in sev_issues if _safe(i.get("status")) == "Escalated")),
            str(len(sev_issues)),
        ])
    dist_rows.append(["TOTAL", str(open_count), "-", str(fixed), "-", str(len(issues))])

    pdf.add_table(
        ["Severity", "Open", "Accepted", "Fixed", "Escalated", "Total"],
        dist_rows,
        [30, 28, 30, 28, 32, 28],
    )

    # ASCII severity bar chart
    pdf.ln(5)
    pdf.subsection_title("Severity Overview")
    max_val = max(critical, major, minor, 1)
    for label, count, color in [("Critical", critical, (204, 0, 0)), ("Major", major, (255, 165, 0)), ("Minor", minor, (0, 112, 192))]:
        bar_width = (count / max_val) * 120 if max_val > 0 else 0
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(51, 51, 51)
        pdf.cell(25, 7, label)
        pdf.set_fill_color(*color)
        pdf.cell(bar_width, 7, "", fill=True)
        pdf.cell(15, 7, f"  {count}", new_x="LMARGIN", new_y="NEXT")

    # ══════════════════════════════════════════════════════════════════════════
    # 5. DETAILED FINDINGS (by Section)
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("5", "Detailed Findings")

    if not issues:
        pdf.body_text("No findings were identified during this review.")
    else:
        # Group by drawing_ref
        drawing_groups: dict[str, list] = {}
        for iss in issues:
            ref = _safe(iss.get("drawing_ref"), "General")
            drawing_groups.setdefault(ref, []).append(iss)

        for drawing_ref, group_issues in drawing_groups.items():
            pdf.subsection_title(f"Section: {drawing_ref}")

            for idx, issue in enumerate(group_issues, 1):
                sev = _safe(issue.get("severity"), "Minor")
                status = _safe(issue.get("status"), "Open")

                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(51, 51, 51)
                pdf.cell(0, 7, _sanitize(f"#{idx}  {_safe(issue.get('issue_type'))}"), new_x="LMARGIN", new_y="NEXT")

                # Metadata line
                pdf.set_font("Helvetica", "", 9)
                pdf.cell(0, 5, _sanitize(
                    f"Severity: {sev}  |  Status: {status}  |  "
                    f"Location: {_safe(issue.get('location'))}  |  "
                    f"Agent: {_safe(issue.get('agent_source'))}"
                ), new_x="LMARGIN", new_y="NEXT")

                # Description
                desc = _safe(issue.get("description"), "No description provided.")
                pdf.set_font("Helvetica", "", 9)
                pdf.multi_cell(0, 4.5, _sanitize(f"Description: {desc}"))

                # Suggested fix
                fix = _safe(issue.get("suggested_fix"), "")
                if fix and fix != "N/A":
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.set_text_color(0, 128, 0)
                    pdf.multi_cell(0, 4.5, _sanitize(f"Corrective Action: {fix}"))
                    pdf.set_text_color(51, 51, 51)

                # Code clause
                clause = _safe(issue.get("code_clause"), "")
                if clause and clause != "N/A":
                    pdf.set_font("Helvetica", "", 8)
                    pdf.set_text_color(31, 78, 121)
                    pdf.cell(0, 5, _sanitize(f"Standard Ref: {clause}"), new_x="LMARGIN", new_y="NEXT")
                    pdf.set_text_color(51, 51, 51)

                pdf.ln(3)

    # ══════════════════════════════════════════════════════════════════════════
    # 6. ANNOTATIONS & LOCATION MAP
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("6", "Annotations & Location Map")

    pdf.body_text(
        "The following table maps each finding to its detected location on the engineering drawings. "
        "Locations are derived from AI vision analysis of grid references, zone indicators, and structural element positions."
    )

    if issues:
        ann_rows = []
        for i, iss in enumerate(issues, 1):
            ann_rows.append([
                str(i),
                _safe(iss.get("drawing_ref"))[:15],
                _safe(iss.get("location"))[:20],
                _safe(iss.get("severity")),
                _safe(iss.get("issue_type"))[:25],
            ])
        pdf.add_table(
            ["#", "Drawing", "Location", "Severity", "Issue Type"],
            ann_rows[:30],  # Limit to 30 for readability
            [12, 35, 45, 28, 60],
        )

    # ══════════════════════════════════════════════════════════════════════════
    # 7. NCRs
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("7", "Non-Conformance Reports (NCRs)")

    if not ncrs:
        pdf.body_text("No NCRs raised.")
    else:
        pdf.body_text(f"{len(ncrs)} NCR(s) raised for non-conformances.")
        ncr_rows = []
        for ncr in ncrs:
            ncr_rows.append([
                f"NCR-{_safe(ncr.get('id'))[:6].upper()}",
                _safe(ncr.get("severity")),
                _safe(ncr.get("drawing_ref"))[:15],
                _safe(ncr.get("description"))[:40],
                _safe(ncr.get("code_clause"))[:20],
            ])
        pdf.add_table(
            ["NCR ID", "Severity", "Drawing", "Description", "Code"],
            ncr_rows,
            [25, 22, 30, 70, 35],
        )

    # ══════════════════════════════════════════════════════════════════════════
    # 8. RFIs
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("8", "Requests for Information (RFIs)")

    if not rfis:
        pdf.body_text("No RFIs raised.")
    else:
        pdf.body_text(f"{len(rfis)} RFI(s) submitted for clarification.")
        rfi_rows = []
        for rfi in rfis:
            rfi_rows.append([
                f"RFI-{_safe(rfi.get('id'))[:6].upper()}",
                _safe(rfi.get("drawing_ref"))[:15],
                _safe(rfi.get("question"))[:50],
                _safe(rfi.get("created_at"))[:10],
            ])
        pdf.add_table(
            ["RFI ID", "Drawing", "Question", "Date"],
            rfi_rows,
            [25, 30, 100, 25],
        )

    # ══════════════════════════════════════════════════════════════════════════
    # 9. STANDARDS REFERENCES
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("9", "Applicable Standards & References")

    if building_codes:
        for code in building_codes:
            pdf.body_text(f"  - {code}")
    else:
        standard_list = [
            "IBC - International Building Code (2021 Edition)",
            "ACI 318 - Building Code Requirements for Structural Concrete",
            "AISC 360 - Specification for Structural Steel Buildings",
            "ASCE 7 - Minimum Design Loads and Associated Criteria",
            "NEC (NFPA 70) - National Electrical Code",
            "ASHRAE 90.1 - Energy Standard for Buildings",
            "ADA Standards for Accessible Design",
            "OSHA 29 CFR 1926 - Construction Industry Safety Standards",
            "IS 456 - Plain and Reinforced Concrete (Indian Standard)",
            "IS 1893 - Criteria for Earthquake Resistant Design",
        ]
        for code in standard_list:
            pdf.body_text(f"  - {code}")

    # Referenced standards from findings
    referenced_codes = set()
    for iss in issues:
        clause = _safe(iss.get("code_clause"), "")
        if clause and clause != "N/A":
            referenced_codes.add(clause)

    if referenced_codes:
        pdf.ln(3)
        pdf.subsection_title("Standards Referenced in Findings")
        for code in sorted(referenced_codes):
            pdf.body_text(f"  - {code}")

    # ══════════════════════════════════════════════════════════════════════════
    # 10. AUDIT TRAIL
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("10", "Audit Trail")

    if audit_logs:
        log_rows = []
        for log in audit_logs[-30:]:
            log_rows.append([
                _safe(log.get("timestamp"))[:19].replace("T", " "),
                _safe(log.get("action")).replace("_", " ").title()[:20],
                _safe(log.get("user_email"))[:20],
                _safe(log.get("details"))[:35],
            ])
        pdf.add_table(
            ["Timestamp", "Action", "User", "Details"],
            log_rows,
            [40, 35, 40, 65],
        )
    else:
        pdf.body_text("No audit trail entries recorded.")

    # ── Footer disclaimer ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(0, 5, _sanitize(
        "DISCLAIMER: This report was generated by ConstructAI - AI-Powered QA/QC Review Platform. "
        "All findings are AI-assisted and should be verified by qualified professionals before "
        "any construction decisions are made. The AI review does not replace professional engineering "
        f"judgment. Report generated on {report_date}."
    ))

    # ── Output ───────────────────────────────────────────────────────────────
    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
